compute_engine_instance:
  image_project: ravyn-images
  image: ravynbuild-0-4-b10
  platform: freebsd
  cpu: 8
  memory: 16G
  disk: 80

build_task:
  timeout_in: 60m
  environment:
    PKG_CONFIG_PATH: /usr/libdata/pkgconfig:/usr/local/libdata/pkgconfig
  script:
    - fetch -o /tmp/ravynOS.txz  https://api.cirrus-ci.com/v1/artifact/github/mszoek/airyx/ravynOS/ravynOS/dist/ravynOS.txz 
    - tar -C / -xvf /tmp/ravynOS.txz
    - make 
    - tar cJvf Terminal.app.txz Terminal.app
  only_if: $CIRRUS_BRANCH == 'main'
  app_artifacts:
    path: "*.app.txz"
